name: Download sing-box via direct URL

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download from GitHub storage
        run: |
          curl -L \
            https://objects.githubusercontent.com/github-production-release-asset-2e65be/47645840/170955938?X-Amz-Algorithm=AWS4-HMAC-SHA256 \
            -o sing-box-1.8.10-linux-amd64.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sing-box
          path: sing-box-1.8.10-linux-amd64.tar.gz
