name: Download sing-box

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          wget https://github.com/SagerNet/sing-box/releases/download/v1.8.10/sing-box-1.8.10-linux-amd64.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sing-box
          path: sing-box-1.8.10-linux-amd64.tar.gz
